name: Build and Push Docker Image

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and publish Docker image
        uses: macbre/push-to-ghcr@v17
        with:
          image_name: ${{ github.repository }}
          image_tag: ${{ github.ref_name }}, latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
